"""initial schema: companies, signals, scores

Revision ID: 1b3848e38506
Revises: 
Create Date: 2026-04-09 04:45:14.116289
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b3848e38506'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('urls', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_companies_discovered_at', 'companies', ['discovered_at'], unique=False)
    op.create_index('ix_companies_domain', 'companies', ['domain'], unique=True)
    op.create_index('ix_companies_name', 'companies', ['name'], unique=False)
    op.create_index('ix_companies_source', 'companies', ['source'], unique=False)
    op.create_index('ix_companies_status', 'companies', ['status'], unique=False)
    op.create_table('scores',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('signal_strength', sa.Float(), nullable=True),
    sa.Column('market_potential', sa.Float(), nullable=True),
    sa.Column('momentum', sa.Float(), nullable=True),
    sa.Column('team_quality', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('scored_by', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scores_company_id', 'scores', ['company_id'], unique=False)
    op.create_index('ix_scores_created_at', 'scores', ['created_at'], unique=False)
    op.create_index('ix_scores_overall', 'scores', ['overall'], unique=False)
    op.create_table('signals',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('signal_type', sa.Enum('FUNDING', 'PRODUCT_LAUNCH', 'HN_MENTION', 'HN_TRENDING', 'X_MENTION', 'X_TRENDING', 'GOOGLE_NEWS', 'HIRING_SURGE', 'PARTNERSHIP', 'AWARD', 'OTHER', name='signaltype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_company_id', 'signals', ['company_id'], unique=False)
    op.create_index('ix_signals_created_at', 'signals', ['created_at'], unique=False)
    op.create_index('ix_signals_signal_type', 'signals', ['signal_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signals_signal_type', table_name='signals')
    op.drop_index('ix_signals_created_at', table_name='signals')
    op.drop_index('ix_signals_company_id', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_scores_overall', table_name='scores')
    op.drop_index('ix_scores_created_at', table_name='scores')
    op.drop_index('ix_scores_company_id', table_name='scores')
    op.drop_table('scores')
    op.drop_index('ix_companies_status', table_name='companies')
    op.drop_index('ix_companies_source', table_name='companies')
    op.drop_index('ix_companies_name', table_name='companies')
    op.drop_index('ix_companies_domain', table_name='companies')
    op.drop_index('ix_companies_discovered_at', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
